### ISSUE TITLE
Gazebo PR2's grasp speed is different with Real PR2 even when sending same goal

### ISSUE THREAD

**Issue by aginika** [PR2/pr2_common#245]
Gazebo's PR2's grasping speed is slower than real one like below.

![slow_grasp_small](https://cloud.githubusercontent.com/assets/3803922/11654898/8d5eba56-9dec-11e5-89a2-9193b9c66642.gif)

The msg I sent is like below

```
header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs: 0
  frame_id: ''
goal_id: 
  stamp: 
    secs: 0
    nsecs: 0
  id: 894907000000_/pr__eus_interface_1449574181000751639_21524_/r_gripper_controller/gripper_action_1
goal: 
  command: 
    position: 0.0
    max_effort: 20.0
```

In this msg , max_effort is set to 20.0, when we set this to 2000, the grapsing speed is normal and no problem. But acctually this is differ from real robot, because 20.0 is enough for real robot.

If I change the value of gripper transmissions's simulated_reduction from 3141.6 to 314.6, this will repair the behavior. (https://github.com/aginika/pr2_common/blob/speed-up-grasp/pr2_description/urdf/gripper_v0/gripper.transmission.xacro#L45 )

![fast_grasp_small](https://cloud.githubusercontent.com/assets/3803922/11654999/61bc7234-9ded-11e5-9ee6-4aa98edd8538.gif)

But I don't understand why cause this and whether above solution is right or not...

Thanks
